packages:
  - apps/server
  - apps/web/pms
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - bcrypt
  - core-js
  - inferno
  - prisma
  - sharp
  - unrs-resolver
