import type { CrmCostPlanPreviewResponse } from '@ssoo/types/crm';

const currentYear = new Date().getFullYear();

export const costPlanPreviewFallback: CrmCostPlanPreviewResponse = {
  summary: {
    year: currentYear,
    rowCount: 0,
    pipelineInternalCostTotal: 0,
    pipelineExternalCostTotal: 0,
    contractInternalCostTotal: 0,
    contractExternalPlanTotal: 0,
    contractExternalActualTotal: 0,
    internalCostCandidateTotal: 0,
    internalCostPlanInputTotal: 0,
    internalCostActualInputTotal: 0,
    internalCostGapTotal: 0,
    internalCostInputRowCount: 0,
    internalCostConfirmedRowCount: 0,
    externalCostPlanCandidateTotal: 0,
    externalCostGapTotal: 0,
    amsExternalCostPlanInputTotal: 0,
    amsExternalCostActualInputTotal: 0,
    amsExternalCostGapTotal: 0,
    amsExternalCostInputRowCount: 0,
    amsExternalCostConfirmedRowCount: 0,
    amsMappedCount: 0,
    amsReadyCount: 0,
    amsBlockedCount: 0,
    activeFilters: {
      year: currentYear,
      businessType: '',
      industryLine: '',
      region: 'all',
      search: '',
    },
    businessTypeOptions: [],
    industryLineOptions: [],
    sourceTypes: ['opportunity-cost', 'contract-cost', 'contract-billing-actual', 'internal-cost-input', 'ams-vendor-mapping', 'ams-external-cost-input', 'ams-readiness'],
    boundaryNotice: 'CRM 원가/AMS preview는 영업기회/계약 원가 라인, 확정 계약 외부원가 계획/실적, 내부원가 월별 입력/확정 원장, AMS 업체-WBS 매핑 원장, AMS 외부원가 월별 입력/정산 확정 원장을 조합합니다.',
    unavailableActions: [],
  },
  months: Array.from({ length: 12 }, (_, index) => ({
    month: index + 1,
    pipelineInternalCostAmount: 0,
    pipelineExternalCostAmount: 0,
    contractInternalCostAmount: 0,
    internalCostPlanInputAmount: 0,
    internalCostActualInputAmount: 0,
    internalCostGapAmount: 0,
    contractExternalPlanAmount: 0,
    contractExternalActualAmount: 0,
    amsExternalCostPlanInputAmount: 0,
    amsExternalCostActualInputAmount: 0,
    amsExternalCostGapAmount: 0,
    externalCostPlanCandidateAmount: 0,
    externalCostGapAmount: 0,
  })),
  rows: [],
  internalCostSourceGrid: {
    targetYear: currentYear,
    items: [
      ['labor', '인건비'],
      ['other', '기타'],
      ['dept_adj', '사업부간조정'],
      ['svc', '매출원가용역'],
      ['dept_common', '사업부공통'],
    ].map(([itemCode, itemName]) => ({
      itemCode: itemCode as 'labor' | 'other' | 'dept_adj' | 'svc' | 'dept_common',
      itemName,
      monthlyPlanAmounts: Array.from({ length: 12 }, () => 0),
      monthlyActualAmounts: Array.from({ length: 12 }, () => 0),
      planAmountTotal: 0,
      actualAmountTotal: 0,
      differenceAmountTotal: 0,
    })),
    boundaryNotice: '원본 호환 내부원가는 연도별 인건비·기타·사업부간조정·매출원가용역·사업부공통의 계획/실적 12개월 값을 저장하며, 차이는 원본과 동일하게 계획-실적으로 계산합니다.',
  },
  amsSourceWorkspace: {
    targetYear: currentYear,
    eligibleWbs: [],
    vendors: [],
    externalCostRows: [],
    boundaryNotice: '원본 호환 AMS는 사업년도별 공급업체 마스터, 확정된 AMS 계약의 복수 WBS 매핑, 업체×WBS별 연간 계획/실적을 관리하며 차이는 실적-계획으로 계산합니다.',
  },
};
