import type { CrmCostPlanPreviewResponse } from '@ssoo/types/crm';

const currentYear = new Date().getFullYear();

export const costPlanPreviewFallback: CrmCostPlanPreviewResponse = {
  summary: {
    year: currentYear,
    rowCount: 0,
    pipelineInternalCostTotal: 0,
    pipelineExternalCostTotal: 0,
    contractInternalCostTotal: 0,
    contractExternalPlanTotal: 0,
    contractExternalActualTotal: 0,
    internalCostCandidateTotal: 0,
    internalCostPlanInputTotal: 0,
    internalCostActualInputTotal: 0,
    internalCostGapTotal: 0,
    internalCostInputRowCount: 0,
    internalCostConfirmedRowCount: 0,
    externalCostPlanCandidateTotal: 0,
    externalCostGapTotal: 0,
    amsExternalCostPlanInputTotal: 0,
    amsExternalCostActualInputTotal: 0,
    amsExternalCostGapTotal: 0,
    amsExternalCostInputRowCount: 0,
    amsExternalCostConfirmedRowCount: 0,
    amsMappedCount: 0,
    amsReadyCount: 0,
    amsBlockedCount: 0,
    activeFilters: {
      year: currentYear,
      businessType: '',
      industryLine: '',
      region: 'all',
      search: '',
    },
    businessTypeOptions: [],
    industryLineOptions: [],
    sourceTypes: ['opportunity-cost', 'contract-cost', 'contract-billing-actual', 'internal-cost-input', 'ams-vendor-mapping', 'ams-external-cost-input', 'ams-readiness'],
    boundaryNotice: 'CRM 원가/AMS preview는 영업기회/계약 원가 라인, 확정 계약 외부원가 계획/실적, 내부원가 월별 입력/확정 원장, AMS 업체-WBS 매핑 원장, AMS 외부원가 월별 입력/정산 확정 원장을 조합합니다.',
    unavailableActions: [],
  },
  months: Array.from({ length: 12 }, (_, index) => ({
    month: index + 1,
    pipelineInternalCostAmount: 0,
    pipelineExternalCostAmount: 0,
    contractInternalCostAmount: 0,
    internalCostPlanInputAmount: 0,
    internalCostActualInputAmount: 0,
    internalCostGapAmount: 0,
    contractExternalPlanAmount: 0,
    contractExternalActualAmount: 0,
    amsExternalCostPlanInputAmount: 0,
    amsExternalCostActualInputAmount: 0,
    amsExternalCostGapAmount: 0,
    externalCostPlanCandidateAmount: 0,
    externalCostGapAmount: 0,
  })),
  rows: [],
};
