#!/usr/bin/env node

/**
 * 문서 검증 스크립트 (Document Linter)
 * 
 * 검증 항목:
 * 1. 파일 네이밍: kebab-case (소문자 + 하이픈)
 * 2. Changelog 섹션: 수동 문서에 필수
 * 3. 문서 위치: 허용된 디렉토리 구조
 * 4. 필수 헤더: 제목 (H1)
 * 
 * 사용법:
 *   node scripts/check-docs.js [files...]
 *   node scripts/check-docs.js --all
 */

const fs = require('fs');
const path = require('path');

// ============================================================
// 설정
// ============================================================

const DOCS_ROOT = path.join(__dirname, '..', 'docs');

// 자동 생성 문서 경로 (Changelog 검증 제외)
const AUTO_GENERATED_PATHS = [
  /\/reference\//,    // 모든 reference/ 폴더
  /^CHANGELOG\.md$/,  // 루트 CHANGELOG
];

// Changelog 검증 제외 경로
const CHANGELOG_EXEMPT_PATHS = [
  /\/_archive\//,     // 아카이브 폴더
  /\/reference\//,    // 자동 생성 폴더
];

// 허용된 디렉토리 구조
const ALLOWED_DIRECTORIES = {
  // 도메인별 (pms, dms, common)
  domain: [
    'architecture',  // 아키텍처 결정, 표준
    'design',        // UI/UX 설계
    'domain',        // 비즈니스 개념
    'guides',        // 가이드라인
    'planning',      // 백로그, 로드맵, 체인지로그
    'tests',         // 테스트 시나리오
    'reference',     // 자동 생성 (api, db, typedoc, storybook)
    '_archive',      // 아카이브
  ],
  // 공통 (common 전용)
  common: [
    'architecture',
    'guides', 
    'reference',
  ],
};

// 파일 네이밍 패턴
const FILE_NAME_PATTERN = /^[a-z0-9]+(-[a-z0-9]+)*\.md$/;
const README_PATTERN = /^README\.md$/;
const ADR_PATTERN = /^adr-\d{3}-[a-z0-9]+(-[a-z0-9]+)*\.md$/;
// 특수 파일 (대문자 허용)
const SPECIAL_FILES = ['CHANGELOG.md', 'AGENTS.md', 'README.md', 'LICENSE.md'];

// ============================================================
// 유틸리티
// ============================================================

const RED = '\x1b[31m';
const YELLOW = '\x1b[33m';
const GREEN = '\x1b[32m';
const RESET = '\x1b[0m';

function isAutoGenerated(filePath) {
  const relativePath = path.relative(DOCS_ROOT, filePath);
  return AUTO_GENERATED_PATHS.some(pattern => pattern.test(relativePath));
}

function getRelativePath(filePath) {
  const projectRoot = path.join(__dirname, '..');
  return path.relative(projectRoot, filePath);
}

// ============================================================
// 검증 함수
// ============================================================

/**
 * 파일 네이밍 검증 (kebab-case)
 */
function checkFileName(filePath) {
  const fileName = path.basename(filePath);
  const errors = [];

  // 특수 파일 허용 (README, CHANGELOG, AGENTS 등)
  if (SPECIAL_FILES.includes(fileName)) {
    return errors;
  }

  // _archive 폴더는 네이밍 규칙 완화
  if (filePath.includes('/_archive/')) {
    return errors;
  }

  // ADR 패턴 확인
  if (fileName.startsWith('adr-')) {
    if (!ADR_PATTERN.test(fileName)) {
      errors.push({
        type: 'naming',
        message: `ADR 파일은 'adr-NNN-description.md' 형식이어야 합니다: ${fileName}`,
        severity: 'error',
      });
    }
    return errors;
  }

  // 일반 파일 kebab-case 확인
  if (!FILE_NAME_PATTERN.test(fileName)) {
    errors.push({
      type: 'naming',
      message: `파일명은 kebab-case (소문자 + 하이픈)여야 합니다: ${fileName}`,
      severity: 'error',
    });
  }

  return errors;
}

/**
 * Changelog 섹션 검증
 */
function checkChangelog(filePath, content) {
  const errors = [];
  const relativePath = path.relative(DOCS_ROOT, filePath);

  // 자동 생성 문서 및 아카이브는 제외
  if (isAutoGenerated(filePath) || 
      CHANGELOG_EXEMPT_PATHS.some(p => p.test(relativePath))) {
    return errors;
  }

  // README.md, CHANGELOG.md, AGENTS.md는 Changelog 필수 아님
  const fileName = path.basename(filePath);
  if (SPECIAL_FILES.includes(fileName)) {
    return errors;
  }

  // Changelog 섹션 확인
  const hasChangelog = /^##\s*Changelog/m.test(content) || 
                       /^\| 날짜 \| 변경 내용 \|/m.test(content);

  if (!hasChangelog) {
    errors.push({
      type: 'changelog',
      message: 'Changelog 섹션이 필요합니다 (## Changelog)',
      severity: 'warning',
    });
  }

  return errors;
}

/**
 * 필수 헤더 검증 (H1 제목)
 */
function checkHeader(filePath, content) {
  const errors = [];

  // H1 헤더 확인
  const hasH1 = /^#\s+.+/m.test(content);

  if (!hasH1) {
    errors.push({
      type: 'header',
      message: 'H1 제목(# 제목)이 필요합니다',
      severity: 'error',
    });
  }

  return errors;
}

/**
 * 문서 위치 검증
 */
function checkLocation(filePath) {
  const errors = [];
  const relativePath = path.relative(DOCS_ROOT, filePath);
  const parts = relativePath.split(path.sep);

  // docs/ 루트 파일은 허용 (CHANGELOG.md, README.md, getting-started.md)
  if (parts.length === 1) {
    return errors;
  }

  // 도메인 루트의 README.md 허용 (docs/pms/README.md)
  if (parts.length === 2 && parts[1] === 'README.md') {
    return errors;
  }

  // common 루트의 특수 파일 허용 (AGENTS.md)
  if (parts.length === 2 && parts[0] === 'common' && SPECIAL_FILES.includes(parts[1])) {
    return errors;
  }

  const domain = parts[0]; // common, pms, dms
  const directory = parts[1]; // architecture, design, etc.

  // 도메인 확인
  if (!['common', 'pms', 'dms'].includes(domain)) {
    errors.push({
      type: 'location',
      message: `알 수 없는 도메인: ${domain} (common, pms, dms만 허용)`,
      severity: 'error',
    });
    return errors;
  }

  // 디렉토리 확인
  const allowedDirs = domain === 'common' 
    ? ALLOWED_DIRECTORIES.common 
    : ALLOWED_DIRECTORIES.domain;

  if (!allowedDirs.includes(directory)) {
    errors.push({
      type: 'location',
      message: `허용되지 않은 디렉토리: ${directory} (허용: ${allowedDirs.join(', ')})`,
      severity: 'error',
    });
  }

  return errors;
}

/**
 * 파일 하나 검증
 */
function validateFile(filePath) {
  const errors = [];

  // 마크다운 파일만
  if (!filePath.endsWith('.md')) {
    return { filePath, errors: [], skipped: true };
  }

  // 파일 읽기
  let content;
  try {
    content = fs.readFileSync(filePath, 'utf-8');
  } catch (e) {
    errors.push({
      type: 'read',
      message: `파일을 읽을 수 없습니다: ${e.message}`,
      severity: 'error',
    });
    return { filePath, errors };
  }

  // 검증 수행
  errors.push(...checkFileName(filePath));
  errors.push(...checkHeader(filePath, content));
  errors.push(...checkChangelog(filePath, content));
  errors.push(...checkLocation(filePath));

  return { filePath, errors };
}

/**
 * 모든 문서 파일 찾기
 */
function findAllDocs() {
  const files = [];
  
  function walk(dir) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        // node_modules, .git 등 제외
        if (!entry.name.startsWith('.') && entry.name !== 'node_modules') {
          walk(fullPath);
        }
      } else if (entry.name.endsWith('.md')) {
        files.push(fullPath);
      }
    }
  }
  
  walk(DOCS_ROOT);
  return files;
}

// ============================================================
// 메인
// ============================================================

function main() {
  const args = process.argv.slice(2);
  let files;

  if (args.includes('--all') || args.length === 0) {
    files = findAllDocs();
  } else {
    // 제공된 파일만 검증
    files = args
      .filter(f => f.endsWith('.md'))
      .map(f => path.resolve(f))
      .filter(f => fs.existsSync(f));
  }

  if (files.length === 0) {
    console.log('검증할 문서가 없습니다.');
    process.exit(0);
  }

  console.log(`\n📄 문서 검증: ${files.length}개 파일\n`);

  let totalErrors = 0;
  let totalWarnings = 0;
  const results = [];

  for (const file of files) {
    const result = validateFile(file);
    if (result.skipped) continue;

    const fileErrors = result.errors.filter(e => e.severity === 'error');
    const fileWarnings = result.errors.filter(e => e.severity === 'warning');

    totalErrors += fileErrors.length;
    totalWarnings += fileWarnings.length;

    if (result.errors.length > 0) {
      results.push(result);
    }
  }

  // 결과 출력
  for (const result of results) {
    console.log(`${getRelativePath(result.filePath)}`);
    for (const error of result.errors) {
      const color = error.severity === 'error' ? RED : YELLOW;
      const icon = error.severity === 'error' ? '✗' : '⚠';
      console.log(`  ${color}${icon} [${error.type}] ${error.message}${RESET}`);
    }
    console.log();
  }

  // 요약
  console.log('─'.repeat(50));
  if (totalErrors === 0 && totalWarnings === 0) {
    console.log(`${GREEN}✓ 모든 문서 검증 통과${RESET}`);
  } else {
    console.log(`결과: ${RED}${totalErrors} 에러${RESET}, ${YELLOW}${totalWarnings} 경고${RESET}`);
  }

  // 에러가 있으면 종료 코드 1
  process.exit(totalErrors > 0 ? 1 : 0);
}

main();
