-- =========================================================
-- CRM Seed Data: Demo Opportunities
-- Schema: crm
-- =========================================================

begin;

insert into crm.crm_opportunity_m (
  opportunity_code, opportunity_group_code, customer_name, opportunity_name, owner_name, owner_user_id,
  business_type, industry_line, region_code, status_code, priority_code,
  version_no, confirmed, expected_start_date, expected_end_date,
  payment_term_code, quote_status_code, quote_client_contact_name, quote_issued_at, quote_valid_until, quote_memo,
  revenue_subtotal, special_discount_type_code, special_discount_value,
  special_discount_amount, revenue_total, cost_total, pms_handoff_status_code, dms_link_status_code,
  admin_boundary_code, next_action, is_active, created_at, updated_at,
  last_source, last_activity
)
values
  ('crm-opp-001', 'crm-opp-001', 'LS Electric', '스마트 배전반 통합 관제 고도화', '김민준',
   (select u.user_id from common.cm_user_m u join common.cm_user_auth_m a on a.user_id = u.user_id where a.login_id = 'am.park' limit 1),
   'SI 구축', '전력/제조', 'domestic', 'proposal', 'high',
   3, false, date '2026-07-01', date '2026-12-31',
   'NET30', 'review', '홍길동', timestamp with time zone '2026-06-08T09:30:00Z', date '2026-07-08', '고객 검토 전 내부 금액 기준 확인',
   840000000, 'amount', 20000000.00, 20000000, 820000000, 592000000, 'planned', 'planned',
   'shared-admin', '제안 금액 검토 후 계약 후보 전환 여부 결정', true,
   timestamp with time zone '2026-06-08T09:20:00Z', timestamp with time zone '2026-06-08T09:20:00Z',
   'SEED', 'crm.opportunity.seed'),
  ('crm-opp-002', 'crm-opp-002', 'LS Cable & System', '해외 공장 품질 데이터 허브', '박서연',
   (select u.user_id from common.cm_user_m u join common.cm_user_auth_m a on a.user_id = u.user_id where a.login_id = 'am.park' limit 1),
   '데이터 플랫폼', '제조/품질', 'overseas', 'qualified', 'high',
   2, false, date '2026-08-15', date '2027-02-28',
   '분할납부', 'draft', 'Jane Lee', null, null, '해외 법인 수금조건 확정 후 견적 검토',
   1260000000, 'rate', 2.50, 31500000, 1228500000, 884000000, 'planned', 'planned',
   'shared-admin', '해외 법인 범위와 수금조건 확정', true,
   timestamp with time zone '2026-06-08T08:45:00Z', timestamp with time zone '2026-06-08T08:45:00Z',
   'SEED', 'crm.opportunity.seed'),
  ('crm-opp-003', 'crm-opp-003', 'LS MnM', '설비 예방정비 모바일 업무화', '이현우',
   (select u.user_id from common.cm_user_m u join common.cm_user_auth_m a on a.user_id = u.user_id where a.login_id = 'pm.kim' limit 1),
   '업무 시스템', '설비/정비', 'domestic', 'won', 'medium',
   4, true, date '2026-07-15', date '2026-11-30',
   '계약즉시', 'accepted', '정비기획팀', timestamp with time zone '2026-06-07T15:30:00Z', date '2026-07-07', '계약 전환 전 고객 수락 기준 보관',
   520000000, 'amount', null, 0, 520000000, 361000000, 'planned', 'planned',
   'shared-admin', '계약 원장 확정 후 PMS 읽기용 인계 패킷 준비', true,
   timestamp with time zone '2026-06-07T15:10:00Z', timestamp with time zone '2026-06-07T15:10:00Z',
   'SEED', 'crm.opportunity.seed'),
  ('crm-opp-004', 'crm-opp-004', 'LS Materials', '영업/생산 수요 예측 PoC', '정다은',
   (select u.user_id from common.cm_user_m u join common.cm_user_auth_m a on a.user_id = u.user_id where a.login_id = 'con.jung' limit 1),
   'AI/분석', '소재/생산', 'domestic', 'draft', 'medium',
   1, false, date '2026-09-01', date '2026-10-31',
   '납품후', 'draft', null, null, null, null,
   180000000, 'amount', null, 0, 180000000, 129000000, 'planned', 'planned',
   'shared-admin', '성과 기준과 확장 옵션 정리', true,
   timestamp with time zone '2026-06-06T11:00:00Z', timestamp with time zone '2026-06-06T11:00:00Z',
   'SEED', 'crm.opportunity.seed'),
  ('crm-opp-005', 'crm-opp-005', 'LS ITC', '그룹 공통 문서/계약 템플릿 체계', '최윤서',
   (select u.user_id from common.cm_user_m u join common.cm_user_auth_m a on a.user_id = u.user_id where a.login_id = 'sm.choi' limit 1),
   '공통 플랫폼', '그룹 공통', 'domestic', 'hold', 'low',
   1, false, date '2026-10-01', date '2027-01-31',
   'NET60', 'void', null, null, null, 'DMS 템플릿 경계 확인 전 견적 보류',
   310000000, 'amount', null, 0, 310000000, 245000000, 'planned', 'planned',
   'shared-admin', 'DMS 템플릿 소유권과 충돌 여부 확인', true,
   timestamp with time zone '2026-06-05T16:30:00Z', timestamp with time zone '2026-06-05T16:30:00Z',
   'SEED', 'crm.opportunity.seed')
on conflict (opportunity_code) do update set
  opportunity_group_code = excluded.opportunity_group_code,
  customer_name = excluded.customer_name,
  opportunity_name = excluded.opportunity_name,
  owner_name = excluded.owner_name,
  owner_user_id = excluded.owner_user_id,
  business_type = excluded.business_type,
  industry_line = excluded.industry_line,
  region_code = excluded.region_code,
  status_code = excluded.status_code,
  priority_code = excluded.priority_code,
  version_no = excluded.version_no,
  confirmed = excluded.confirmed,
  expected_start_date = excluded.expected_start_date,
  expected_end_date = excluded.expected_end_date,
  payment_term_code = excluded.payment_term_code,
  quote_status_code = excluded.quote_status_code,
  quote_client_contact_name = excluded.quote_client_contact_name,
  quote_issued_at = excluded.quote_issued_at,
  quote_valid_until = excluded.quote_valid_until,
  quote_memo = excluded.quote_memo,
  revenue_subtotal = excluded.revenue_subtotal,
  special_discount_type_code = excluded.special_discount_type_code,
  special_discount_value = excluded.special_discount_value,
  special_discount_amount = excluded.special_discount_amount,
  revenue_total = excluded.revenue_total,
  cost_total = excluded.cost_total,
  pms_handoff_status_code = excluded.pms_handoff_status_code,
  dms_link_status_code = excluded.dms_link_status_code,
  admin_boundary_code = excluded.admin_boundary_code,
  next_action = excluded.next_action,
  is_active = excluded.is_active,
  updated_at = excluded.updated_at,
  last_source = excluded.last_source,
  last_activity = excluded.last_activity;

insert into crm.crm_opportunity_line_d (
  opportunity_id, line_code, line_kind_code, category_code, line_label,
  quantity, unit_price, amount, margin_rate, trunc_unit,
  department, member_name, grade, service_type_code,
  revenue_linked, linked_cost_line_code, revenue_unit_price,
  sort_order, is_active, created_at, updated_at, last_source, last_activity
)
select o.opportunity_id, v.line_code, v.line_kind_code, v.category_code, v.line_label,
       v.quantity, v.unit_price, v.amount, v.margin_rate, v.trunc_unit,
       v.department, v.member_name, v.grade, v.service_type_code,
       v.revenue_linked, v.linked_cost_line_code, v.revenue_unit_price,
       v.sort_order, true, now(), now(), 'SEED', 'crm.opportunity.seed'
from crm.crm_opportunity_m o
join (
  values
    ('crm-opp-001', 'rev-001-1', 'revenue', 'product', '관제 플랫폼 라이선스', 3.00::numeric, 130000000::bigint, 390000000::bigint, null::numeric, 0::bigint, null, null, null, null, false, null, null::bigint, 10),
    ('crm-opp-001', 'rev-001-2', 'revenue', 'service', '구축/연동 서비스', 6.00::numeric, 75000000::bigint, 450000000::bigint, 22.67::numeric, 0::bigint, 'DX센터', '구축팀', 'Senior', 'internal', true, 'cost-001-1', null::bigint, 20),
    ('crm-opp-001', 'cost-001-1', 'cost', 'internal-cost', '내부 수행 원가', 6.00::numeric, 58000000::bigint, 348000000::bigint, null::numeric, 0::bigint, 'DX센터', '수행팀', 'Senior', 'internal', true, null, 75000000::bigint, 30),
    ('crm-opp-001', 'cost-001-2', 'cost', 'external-cost', '외부 연동/장비 원가', 2.00::numeric, 122000000::bigint, 244000000::bigint, null::numeric, 0::bigint, '파트너', '연동 장비', 'Partner', 'external', false, null, null::bigint, 40),
    ('crm-opp-002', 'rev-002-1', 'revenue', 'service', '데이터 수집/정제/대시보드', 9.00::numeric, 140000000::bigint, 1260000000::bigint, null::numeric, 0::bigint, 'Global Data', '데이터 플랫폼팀', 'Principal', 'internal', false, null, null::bigint, 10),
    ('crm-opp-002', 'cost-002-1', 'cost', 'internal-cost', '전담 개발/PM 원가', 9.00::numeric, 78000000::bigint, 702000000::bigint, null::numeric, 0::bigint, 'Global Data', '전담 개발/PM', 'Senior', 'internal', false, null, null::bigint, 20),
    ('crm-opp-002', 'cost-002-2', 'cost', 'external-cost', '현지 인프라/통역/검증', 1.00::numeric, 182000000::bigint, 182000000::bigint, null::numeric, 0::bigint, '해외 법인', '현지 검증', 'Partner', 'external', false, null, null::bigint, 30),
    ('crm-opp-003', 'rev-003-1', 'revenue', 'service', '모바일 업무 구축', 4.00::numeric, 130000000::bigint, 520000000::bigint, null::numeric, 0::bigint, '모바일센터', '앱 구축팀', 'Senior', 'internal', false, null, null::bigint, 10),
    ('crm-opp-003', 'cost-003-1', 'cost', 'internal-cost', '수행 인력 원가', 4.00::numeric, 74500000::bigint, 298000000::bigint, null::numeric, 0::bigint, '모바일센터', '수행 인력', 'Senior', 'internal', false, null, null::bigint, 20),
    ('crm-opp-003', 'cost-003-2', 'cost', 'external-cost', '모바일 단말 검증', 1.00::numeric, 63000000::bigint, 63000000::bigint, null::numeric, 0::bigint, 'QA 파트너', '단말 검증', 'Partner', 'external', false, null, null::bigint, 30),
    ('crm-opp-004', 'rev-004-1', 'revenue', 'service', 'PoC 분석/모델링', 3.00::numeric, 60000000::bigint, 180000000::bigint, null::numeric, 0::bigint, 'AI랩', '분석 모델링', 'Senior', 'internal', false, null, null::bigint, 10),
    ('crm-opp-004', 'cost-004-1', 'cost', 'internal-cost', '분석/검증 원가', 3.00::numeric, 43000000::bigint, 129000000::bigint, null::numeric, 0::bigint, 'AI랩', '분석/검증', 'Senior', 'internal', false, null, null::bigint, 20),
    ('crm-opp-005', 'rev-005-1', 'revenue', 'service', '템플릿/검토 흐름 설계', 2.00::numeric, 155000000::bigint, 310000000::bigint, null::numeric, 0::bigint, '플랫폼팀', '업무 설계', 'Principal', 'internal', false, null, null::bigint, 10),
    ('crm-opp-005', 'cost-005-1', 'cost', 'internal-cost', '업무 설계/구축 원가', 2.00::numeric, 122500000::bigint, 245000000::bigint, null::numeric, 0::bigint, '플랫폼팀', '업무 설계/구축', 'Senior', 'internal', false, null, null::bigint, 20)
) as v(opportunity_code, line_code, line_kind_code, category_code, line_label,
  quantity, unit_price, amount, margin_rate, trunc_unit,
  department, member_name, grade, service_type_code,
  revenue_linked, linked_cost_line_code, revenue_unit_price, sort_order)
  on o.opportunity_code = v.opportunity_code
on conflict (opportunity_id, line_code) do update set
  line_kind_code = excluded.line_kind_code,
  category_code = excluded.category_code,
  line_label = excluded.line_label,
  quantity = excluded.quantity,
  unit_price = excluded.unit_price,
  amount = excluded.amount,
  margin_rate = excluded.margin_rate,
  trunc_unit = excluded.trunc_unit,
  department = excluded.department,
  member_name = excluded.member_name,
  grade = excluded.grade,
  service_type_code = excluded.service_type_code,
  revenue_linked = excluded.revenue_linked,
  linked_cost_line_code = excluded.linked_cost_line_code,
  revenue_unit_price = excluded.revenue_unit_price,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now(),
  last_source = excluded.last_source,
  last_activity = excluded.last_activity;

commit;
